
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 06:30:45 KST (Jul  8 2026 21:30:45 UTC)

// Verification Directory fv/traffic_light 

module traffic_light(clk, rst_n, o_red, o_left, o_green, o_yellow);
  input clk, rst_n;
  output o_red, o_left, o_green, o_yellow;
  wire clk, rst_n;
  wire o_red, o_left, o_green, o_yellow;
  wire [2:0] cnt;
  wire [1:0] state;
  wire n_0, n_2, n_4, n_5, n_6, n_9, n_10, n_12;
  wire n_14, n_15, n_16, n_18, n_19, n_20, n_21, n_25;
  DFFRHQX1 \cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_20), .Q (cnt[2]));
  OAI2BB1X1 g602__2398(.A0N (state[0]), .A1N (n_19), .B0 (n_12), .Y
       (n_21));
  DFFRHQX1 \cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_14), .Q (cnt[1]));
  DFFRHQX1 \cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_16), .Q (cnt[0]));
  AND2XL g605__5107(.A (n_5), .B (n_19), .Y (n_20));
  AO22XL g603__6260(.A0 (o_left), .A1 (n_15), .B0 (state[1]), .B1
       (n_25), .Y (n_18));
  NOR2XL g606__4319(.A (cnt[0]), .B (n_15), .Y (n_16));
  NOR2XL g607__8428(.A (n_10), .B (n_15), .Y (n_14));
  INVX1 g608(.A (n_15), .Y (n_19));
  NAND2X1 g609__5526(.A (n_25), .B (n_12), .Y (n_15));
  MXI2XL g614__1617(.A (o_yellow), .B (o_left), .S0 (cnt[1]), .Y (n_9));
  NAND4BX1 g612__1705(.AN (cnt[0]), .B (cnt[2]), .C (n_6), .D (n_2), .Y
       (n_12));
  XNOR2X1 g613__5122(.A (cnt[2]), .B (n_4), .Y (n_5));
  OAI21X1 g615__8246(.A0 (cnt[0]), .A1 (cnt[1]), .B0 (n_4), .Y (n_10));
  XNOR2X1 g617__7098(.A (cnt[1]), .B (state[1]), .Y (n_2));
  NOR2XL g621__6131(.A (n_6), .B (n_0), .Y (o_yellow));
  NOR2X1 g622__1881(.A (state[1]), .B (n_6), .Y (o_left));
  NAND2XL g619__5115(.A (cnt[0]), .B (cnt[1]), .Y (n_4));
  NOR2XL g618__7482(.A (state[0]), .B (state[1]), .Y (o_red));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_21), .Q
       (state[0]), .QN (n_6));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_18), .Q
       (state[1]), .QN (n_0));
  AO21XL g2(.A0 (state[1]), .A1 (n_6), .B0 (o_left), .Y (o_green));
  OR3XL g634(.A (cnt[2]), .B (n_10), .C (n_9), .Y (n_25));
endmodule

