
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 05:43:05 KST (Jul  7 2026 20:43:05 UTC)

// Verification Directory fv/d_latch 

module d_latch(i_d, clk, o_q);
  input [31:0] i_d;
  input clk;
  output [31:0] o_q;
  wire [31:0] i_d;
  wire clk;
  wire [31:0] o_q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  TLATX1 \o_q_reg[27] (.G (clk), .D (i_d[27]), .Q (o_q[27]), .QN
       (UNCONNECTED));
  TLATX1 \o_q_reg[2] (.G (clk), .D (i_d[2]), .Q (o_q[2]), .QN
       (UNCONNECTED0));
  TLATX1 \o_q_reg[9] (.G (clk), .D (i_d[9]), .Q (o_q[9]), .QN
       (UNCONNECTED1));
  TLATX1 \o_q_reg[30] (.G (clk), .D (i_d[30]), .Q (o_q[30]), .QN
       (UNCONNECTED2));
  TLATX1 \o_q_reg[17] (.G (clk), .D (i_d[17]), .Q (o_q[17]), .QN
       (UNCONNECTED3));
  TLATX1 \o_q_reg[28] (.G (clk), .D (i_d[28]), .Q (o_q[28]), .QN
       (UNCONNECTED4));
  TLATX1 \o_q_reg[24] (.G (clk), .D (i_d[24]), .Q (o_q[24]), .QN
       (UNCONNECTED5));
  TLATX1 \o_q_reg[16] (.G (clk), .D (i_d[16]), .Q (o_q[16]), .QN
       (UNCONNECTED6));
  TLATX1 \o_q_reg[25] (.G (clk), .D (i_d[25]), .Q (o_q[25]), .QN
       (UNCONNECTED7));
  TLATX1 \o_q_reg[0] (.G (clk), .D (i_d[0]), .Q (o_q[0]), .QN
       (UNCONNECTED8));
  TLATX1 \o_q_reg[15] (.G (clk), .D (i_d[15]), .Q (o_q[15]), .QN
       (UNCONNECTED9));
  TLATX1 \o_q_reg[23] (.G (clk), .D (i_d[23]), .Q (o_q[23]), .QN
       (UNCONNECTED10));
  TLATX1 \o_q_reg[7] (.G (clk), .D (i_d[7]), .Q (o_q[7]), .QN
       (UNCONNECTED11));
  TLATX1 \o_q_reg[14] (.G (clk), .D (i_d[14]), .Q (o_q[14]), .QN
       (UNCONNECTED12));
  TLATX1 \o_q_reg[13] (.G (clk), .D (i_d[13]), .Q (o_q[13]), .QN
       (UNCONNECTED13));
  TLATX1 \o_q_reg[10] (.G (clk), .D (i_d[10]), .Q (o_q[10]), .QN
       (UNCONNECTED14));
  TLATX1 \o_q_reg[3] (.G (clk), .D (i_d[3]), .Q (o_q[3]), .QN
       (UNCONNECTED15));
  TLATX1 \o_q_reg[12] (.G (clk), .D (i_d[12]), .Q (o_q[12]), .QN
       (UNCONNECTED16));
  TLATX1 \o_q_reg[11] (.G (clk), .D (i_d[11]), .Q (o_q[11]), .QN
       (UNCONNECTED17));
  TLATX1 \o_q_reg[21] (.G (clk), .D (i_d[21]), .Q (o_q[21]), .QN
       (UNCONNECTED18));
  TLATX1 \o_q_reg[31] (.G (clk), .D (i_d[31]), .Q (o_q[31]), .QN
       (UNCONNECTED19));
  TLATX1 \o_q_reg[1] (.G (clk), .D (i_d[1]), .Q (o_q[1]), .QN
       (UNCONNECTED20));
  TLATX1 \o_q_reg[29] (.G (clk), .D (i_d[29]), .Q (o_q[29]), .QN
       (UNCONNECTED21));
  TLATX1 \o_q_reg[26] (.G (clk), .D (i_d[26]), .Q (o_q[26]), .QN
       (UNCONNECTED22));
  TLATX1 \o_q_reg[20] (.G (clk), .D (i_d[20]), .Q (o_q[20]), .QN
       (UNCONNECTED23));
  TLATX1 \o_q_reg[8] (.G (clk), .D (i_d[8]), .Q (o_q[8]), .QN
       (UNCONNECTED24));
  TLATX1 \o_q_reg[19] (.G (clk), .D (i_d[19]), .Q (o_q[19]), .QN
       (UNCONNECTED25));
  TLATX1 \o_q_reg[6] (.G (clk), .D (i_d[6]), .Q (o_q[6]), .QN
       (UNCONNECTED26));
  TLATX1 \o_q_reg[5] (.G (clk), .D (i_d[5]), .Q (o_q[5]), .QN
       (UNCONNECTED27));
  TLATX1 \o_q_reg[18] (.G (clk), .D (i_d[18]), .Q (o_q[18]), .QN
       (UNCONNECTED28));
  TLATX1 \o_q_reg[4] (.G (clk), .D (i_d[4]), .Q (o_q[4]), .QN
       (UNCONNECTED29));
  TLATX1 \o_q_reg[22] (.G (clk), .D (i_d[22]), .Q (o_q[22]), .QN
       (UNCONNECTED30));
endmodule

