
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 05:57:47 KST (Jul  7 2026 20:57:47 UTC)

// Verification Directory fv/FSM3 

module FSM3(clk, rst_n, go, ws, rd, ds);
  input clk, rst_n, go, ws;
  output rd, ds;
  wire clk, rst_n, go, ws;
  wire rd, ds;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  DFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (state[1]));
  DFFRHQX1 ds_reg(.RN (rst_n), .CK (clk), .D (n_8), .Q (ds));
  OAI21X1 g240__2398(.A0 (state[1]), .A1 (n_4), .B0 (n_7), .Y (n_10));
  OAI211X1 g236__5107(.A0 (state[1]), .A1 (n_1), .B0 (n_0), .C0 (n_3),
       .Y (n_9));
  OR2XL g239__6260(.A (ds), .B (n_6), .Y (n_8));
  INVXL g241(.A (n_6), .Y (n_7));
  OAI2BB1X1 g244__4319(.A0N (go), .A1N (n_4), .B0 (n_2), .Y (n_5));
  NAND2BX1 g243__8428(.AN (n_2), .B (ws), .Y (n_3));
  NOR2X1 g242__5526(.A (ws), .B (n_2), .Y (n_6));
  NAND2X1 g245__6783(.A (state[1]), .B (n_4), .Y (n_2));
  NOR2X1 g246__3680(.A (go), .B (state[0]), .Y (n_1));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_5), .Q
       (state[0]), .QN (n_4));
  DFFRX1 rd_reg(.RN (rst_n), .CK (clk), .D (n_9), .Q (rd), .QN (n_0));
endmodule

